import React, { useState, useEffect, useMemo } from 'react';
import { useLanguage } from '../contexts/LanguageContext';
import { useActionLoading } from '../contexts/ActionLoadingContext';
import { useDialog } from '../contexts/DialogContext';
import { useAccessManager, JobDistributionPayload } from '../../hooks/useAccessManager';
import { 
    BriefcaseIcon, BuildingOfficeIcon, TrashIcon, 
    PlusIcon, FunnelIcon, MapPinIcon, ComputerDesktopIcon, UserIcon
} from "@heroicons/react/24/outline";
import { motion, AnimatePresence } from 'framer-motion';
import { getFirestore, collection, getDocs, onSnapshot, query, orderBy } from "firebase/firestore";

const firestore = getFirestore();

// --- Interfaces ---
interface BasicEntity { id: string; name_ar: string; name_en: string; [key: string]: unknown; }

interface DistributionRule {
    id: string; 
    job_id: string;
    company_id: string;
    sector_id?: string | null;
    department_id?: string | null;
    section_id?: string | null;
    auto_generated?: boolean;
    updated_at?: any;
}

const translations = {
    ar: {
        title: "إدارة توزيع الوظائف",
        subtitle: "تحديد مواقع تواجد الوظائف (الشركات والأقسام).",
        addRule: "توزيع وظيفة جديدة",
        searchPlaceholder: "ابحث عن وظيفة أو شركة...",
        noRules: "لا توجد قواعد توزيع مضافة.",
        autoGenerated: "تلقائي (من الموظفين)",
        manual: "يدوي (إعداد مسبق)",
        job: "الوظيفة",
        location: "الموقع التنظيمي",
        actions: "إجراءات",
        confirmDelete: "هل أنت متأكد من حذف قاعدة التوزيع هذه؟",
        deleteSuccess: "تم حذف التوزيع بنجاح.",
        addSuccess: "تم إضافة التوزيع بنجاح.",
        filterCompany: "تصفية حسب الشركة",
        allCompanies: "كل الشركات",
        // Modal
        selectJob: "اختر الوظيفة",
        selectCompany: "اختر الشركة",
        selectSection: "القسم (اختياري)",
        save: "حفظ التوزيع",
        cancel: "إلغاء",
        saving: "جاري الحفظ...",
        deleting: "جاري الحذف..."
    },
    en: {
        title: "Job Distribution Manager",
        subtitle: "Define where jobs exist (Companies and Sections).",
        addRule: "Distribute New Job",
        searchPlaceholder: "Search job or company...",
        noRules: "No distribution rules found.",
        autoGenerated: "Auto (From Users)",
        manual: "Manual (Preset)",
        job: "Job Title",
        location: "Location",
        actions: "Actions",
        confirmDelete: "Are you sure you want to delete this rule?",
        deleteSuccess: "Rule deleted successfully.",
        addSuccess: "Rule added successfully.",
        filterCompany: "Filter by Company",
        allCompanies: "All Companies",
        // Modal
        selectJob: "Select Job",
        selectCompany: "Select Company",
        selectSection: "Section (Optional)",
        save: "Save Rule",
        cancel: "Cancel",
        saving: "Saving...",
        deleting: "Deleting..."
    }
};

// --- Helper Component: Location Badge (Simplified) ---
const LocationBadge = ({ rule, lookups, language }: { rule: DistributionRule, lookups: any, language: string }) => {
    const isAr = language === 'ar';
    const getName = (list: BasicEntity[], id: string | null) => {
        if (!id) return null;
        const item = list.find(i => String(i.id) === String(id));
        return item ? (isAr ? item.name_ar : item.name_en) : id;
    };

    const company = getName(lookups.companies, rule.company_id);
    const section = getName(lookups.sections, rule.section_id || null);

    return (
        <div className="flex flex-wrap items-center gap-1 text-xs text-gray-400">
            <span className="flex items-center gap-1 text-gray-300 bg-gray-700/50 px-2 py-0.5 rounded border border-gray-600/50">
                <BuildingOfficeIcon className="w-3 h-3" /> {company}
            </span>
            {section && <span className="text-gray-600">/</span>}
            {section && <span className="text-[#FFD700] bg-[#FFD700]/10 px-1.5 py-0.5 rounded border border-[#FFD700]/20">{section}</span>}
        </div>
    );
};

// --- Modal Component (Simplified) ---
const DistributionModal = ({ isOpen, onClose, onSave, lookups, t, language }: any) => {
    const [formData, setFormData] = useState<JobDistributionPayload>({
        job_id: '',
        company_id: '',
        sector_id: null,     // Ignored
        department_id: null, // Ignored
        section_id: null
    });

    const isAr = language === 'ar';

    // فلترة الأقسام: إذا كان لديك حقل company_id داخل جدول الأقسام، يمكنك تفعيل السطر التالي.
    // حالياً سنعرض كل الأقسام أو نفلترها بناءً على المنطق المتوفر لديك.
    // const filteredSections = lookups.sections.filter((s: any) => !formData.company_id || s.company_id === formData.company_id);
    const filteredSections = lookups.sections; // عرض الكل مؤقتاً لضمان العمل

    const handleSubmit = () => {
        if (!formData.job_id || !formData.company_id) return;
        onSave(formData);
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
            <motion.div 
                initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}
                className="bg-gray-800 border border-gray-700 rounded-xl p-6 w-full max-w-lg shadow-2xl"
            >
                <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2">
                    <PlusIcon className="w-5 h-5 text-blue-400" /> {t.addRule}
                </h3>

                <div className="space-y-4">
                    {/* Job */}
                    <div>
                        <label className="text-xs text-gray-400 mb-1 block">{t.selectJob} <span className="text-red-500">*</span></label>
                        <div className="relative">
                            <select 
                                value={formData.job_id} 
                                onChange={(e) => setFormData({...formData, job_id: e.target.value})}
                                className="w-full bg-gray-900 border border-gray-600 rounded-lg p-2.5 pl-10 text-sm text-white focus:border-blue-500 appearance-none"
                            >
                                <option value="">---</option>
                                {lookups.jobs.map((j: any) => <option key={j.id} value={j.id}>{isAr ? j.name_ar : j.name_en}</option>)}
                            </select>
                            <BriefcaseIcon className="w-5 h-5 text-gray-500 absolute left-3 top-2.5 pointer-events-none" />
                        </div>
                    </div>

                    {/* Company */}
                    <div>
                        <label className="text-xs text-gray-400 mb-1 block">{t.selectCompany} <span className="text-red-500">*</span></label>
                        <div className="relative">
                            <select 
                                value={formData.company_id} 
                                onChange={(e) => setFormData({...formData, company_id: e.target.value})}
                                className="w-full bg-gray-900 border border-gray-600 rounded-lg p-2.5 pl-10 text-sm text-white focus:border-blue-500 appearance-none"
                            >
                                <option value="">---</option>
                                {lookups.companies.map((c: any) => <option key={c.id} value={c.id}>{isAr ? c.name_ar : c.name_en}</option>)}
                            </select>
                            <BuildingOfficeIcon className="w-5 h-5 text-gray-500 absolute left-3 top-2.5 pointer-events-none" />
                        </div>
                    </div>

                    {/* Section - Only Field Remaining */}
                    <div>
                        <label className="text-xs text-gray-400 mb-1 block">{t.selectSection}</label>
                        <select 
                            value={formData.section_id || ''} 
                            onChange={(e) => setFormData({...formData, section_id: e.target.value || null})}
                            className="w-full bg-gray-900 border border-gray-600 rounded-lg p-2.5 text-sm text-white focus:border-blue-500"
                        >
                            <option value="">{t.selectSection}</option>
                            {filteredSections.map((s: any) => <option key={s.id} value={s.id}>{isAr ? s.name_ar : s.name_en}</option>)}
                        </select>
                    </div>
                </div>

                <div className="flex justify-end gap-3 mt-8 pt-4 border-t border-gray-700">
                    <button onClick={onClose} className="px-4 py-2 text-sm text-gray-400 hover:text-white transition-colors">{t.cancel}</button>
                    <button 
                        onClick={handleSubmit} 
                        disabled={!formData.job_id || !formData.company_id}
                        className="bg-blue-500 hover:bg-blue-600 text-white px-6 py-2 rounded-lg font-bold shadow-lg disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                    >
                        {t.save}
                    </button>
                </div>
            </motion.div>
        </div>
    );
};

export default function JobDistributionManager() {
    const { language } = useLanguage();
    const t = translations[language as keyof typeof translations];
    const { showDialog } = useDialog();
    const { showActionLoading, hideActionLoading } = useActionLoading();
    
    const { manageJobDistribution } = useAccessManager();

    const [rules, setRules] = useState<DistributionRule[]>([]);
    const [loading, setLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');
    const [filterCompany, setFilterCompany] = useState('');
    const [isModalOpen, setIsModalOpen] = useState(false);

    // Lookups State (Removed unnecessary sectors/depts fetching if not used for filtering, kept for safety)
    const [lookups, setLookups] = useState({
        jobs: [] as BasicEntity[],
        companies: [] as BasicEntity[],
        sectors: [] as BasicEntity[],
        departments: [] as BasicEntity[],
        sections: [] as BasicEntity[]
    });

    useEffect(() => {
        const fetchLookups = async () => {
            try {
                // Fetching only what's needed mostly, kept structure just in case
                const [j, c, s, d, sec] = await Promise.all([
                    getDocs(collection(firestore, 'jobs')),
                    getDocs(collection(firestore, 'companies')),
                    getDocs(collection(firestore, 'sectors')),
                    getDocs(collection(firestore, 'departments')),
                    getDocs(collection(firestore, 'sections')),
                ]);
                setLookups({
                    jobs: j.docs.map(doc => ({ id: doc.id, ...doc.data() } as BasicEntity)),
                    companies: c.docs.map(doc => ({ id: doc.id, ...doc.data() } as BasicEntity)),
                    sectors: s.docs.map(doc => ({ id: doc.id, ...doc.data() } as BasicEntity)),
                    departments: d.docs.map(doc => ({ id: doc.id, ...doc.data() } as BasicEntity)),
                    sections: sec.docs.map(doc => ({ id: doc.id, ...doc.data() } as BasicEntity)),
                });
            } catch (e) { console.error(e); }
        };
        fetchLookups();

        const q = query(collection(firestore, 'job_distribution'), orderBy('updated_at', 'desc'));
        const unsub = onSnapshot(q, (snap) => {
            const data = snap.docs.map(doc => ({ id: doc.id, ...doc.data() } as DistributionRule));
            setRules(data);
            setLoading(false);
        });

        return () => unsub();
    }, []);

    const handleAdd = async (payload: JobDistributionPayload) => {
        setIsModalOpen(false);
        showActionLoading(t.saving);
        const success = await manageJobDistribution('add', payload);
        hideActionLoading();
        if (success) showDialog({ variant: 'success', title: t.addSuccess, message: "" });
    };

    const handleDelete = (id: string) => {
        showDialog({
            variant: 'confirm',
            title: t.actions,
            message: t.confirmDelete,
            onConfirm: async () => {
                showActionLoading(t.deleting);
                const success = await manageJobDistribution('delete', undefined, id);
                hideActionLoading();
                if (success) showDialog({ variant: 'success', title: t.deleteSuccess, message: "" });
            }
        });
    };

    const filteredRules = rules.filter(r => {
        const jobName = lookups.jobs.find(j => String(j.id) === String(r.job_id))?.[language === 'ar' ? 'name_ar' : 'name_en'] || '';
        const companyName = lookups.companies.find(c => String(c.id) === String(r.company_id))?.[language === 'ar' ? 'name_ar' : 'name_en'] || '';
        
        const matchesSearch = jobName.toLowerCase().includes(searchTerm.toLowerCase()) || 
                              companyName.toLowerCase().includes(searchTerm.toLowerCase());
        const matchesCompany = filterCompany ? String(r.company_id) === String(filterCompany) : true;

        return matchesSearch && matchesCompany;
    });

    return (
        <div className="min-h-screen p-6 max-w-7xl mx-auto pb-20">
            {/* Header */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
                <div>
                    <h1 className="text-2xl font-bold text-white flex items-center gap-2">
                        <MapPinIcon className="w-8 h-8 text-[#FFD700]" />
                        {t.title}
                    </h1>
                    <p className="text-gray-400 text-sm mt-1">{t.subtitle}</p>
                </div>
                <button 
                    onClick={() => setIsModalOpen(true)}
                    className="bg-blue-600 hover:bg-blue-500 text-white px-5 py-2.5 rounded-xl font-bold shadow-lg shadow-blue-600/20 flex items-center gap-2 transition-all"
                >
                    <PlusIcon className="w-5 h-5" /> {t.addRule}
                </button>
            </div>

            {/* Filters */}
            <div className="bg-gray-800/50 border border-gray-700 rounded-xl p-4 mb-6 flex flex-col md:flex-row gap-4">
                <div className="relative flex-1">
                    <input 
                        type="text" 
                        placeholder={t.searchPlaceholder}
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="w-full bg-gray-900 border border-gray-600 rounded-lg py-2.5 px-4 pl-10 focus:border-[#FFD700] transition-colors text-white"
                    />
                    <BriefcaseIcon className="w-5 h-5 text-gray-500 absolute left-3 top-1/2 -translate-y-1/2" />
                </div>
                
                <div className="relative w-full md:w-64">
                    <select 
                        value={filterCompany}
                        onChange={(e) => setFilterCompany(e.target.value)}
                        className="w-full bg-gray-900 border border-gray-600 rounded-lg py-2.5 px-4 pl-10 focus:border-[#FFD700] transition-colors text-white appearance-none"
                    >
                        <option value="">{t.allCompanies}</option>
                        {lookups.companies.map(c => (
                            <option key={c.id} value={c.id}>{language === 'ar' ? c.name_ar : c.name_en}</option>
                        ))}
                    </select>
                    <FunnelIcon className="w-5 h-5 text-gray-500 absolute left-3 top-1/2 -translate-y-1/2" />
                </div>
            </div>

            {/* Content List */}
            {loading ? (
                <div className="text-center py-20 text-gray-500 animate-pulse">Checking records...</div>
            ) : filteredRules.length === 0 ? (
                <div className="text-center py-20 border-2 border-dashed border-gray-700 rounded-xl bg-gray-800/30">
                    <ComputerDesktopIcon className="w-16 h-16 text-gray-600 mx-auto mb-4" />
                    <p className="text-gray-400">{t.noRules}</p>
                </div>
            ) : (
                <div className="grid grid-cols-1 gap-4">
                    <AnimatePresence>
                        {filteredRules.map((rule) => {
                            const jobName = lookups.jobs.find(j => String(j.id) === String(rule.job_id))?.[language === 'ar' ? 'name_ar' : 'name_en'] || rule.job_id;
                            
                            return (
                                <motion.div 
                                    key={rule.id}
                                    layout
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0, scale: 0.95 }}
                                    className="bg-gray-800 border border-gray-700 rounded-xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-4 hover:border-gray-600 transition-colors group"
                                >
                                    <div className="flex items-start gap-4">
                                        <div className={`w-12 h-12 rounded-full flex items-center justify-center shrink-0 ${rule.auto_generated ? 'bg-blue-500/10 text-blue-400 border border-blue-500/20' : 'bg-[#FFD700]/10 text-[#FFD700] border border-[#FFD700]/20'}`}>
                                            {rule.auto_generated ? <UserIcon className="w-6 h-6" /> : <ComputerDesktopIcon className="w-6 h-6" />}
                                        </div>
                                        
                                        <div>
                                            <h3 className="font-bold text-lg text-white mb-1">{jobName}</h3>
                                            
                                            {/* Simplified Location Badge */}
                                            <LocationBadge rule={rule} lookups={lookups} language={language} />
                                            
                                            <div className="mt-2">
                                                <span className={`text-[10px] px-2 py-0.5 rounded border ${rule.auto_generated ? 'bg-blue-900/30 text-blue-300 border-blue-800' : 'bg-green-900/30 text-green-300 border-green-800'}`}>
                                                    {rule.auto_generated ? t.autoGenerated : t.manual}
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    <button 
                                        onClick={() => handleDelete(rule.id)}
                                        className="self-end md:self-center p-2 rounded-lg text-gray-500 hover:bg-red-500/10 hover:text-red-400 transition-colors"
                                        title="Delete"
                                    >
                                        <TrashIcon className="w-5 h-5" />
                                    </button>
                                </motion.div>
                            );
                        })}
                    </AnimatePresence>
                </div>
            )}

            <DistributionModal 
                isOpen={isModalOpen} 
                onClose={() => setIsModalOpen(false)} 
                onSave={handleAdd}
                lookups={lookups}
                t={t}
                language={language}
            />
        </div>
    );
}